//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.AdminPanel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanySchedulesProcessed
    {
        public string strCompanyName { get; set; }
        public int intPayrollScheduleID { get; set; }
        public System.Guid strBatchID { get; set; }
        public long intPayWeekNumber { get; set; }
    }
}
