//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.AdminPanel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompensationItem
    {
        public string strCompensationName { get; set; }
        public string strDescription { get; set; }
        public int intCompensationType { get; set; }
        public int intComputationType { get; set; }
        public bool boolEnabled { get; set; }
        public int intImportType { get; set; }
        public string strGLAccount { get; set; }
        public bool boolCovidCompensation { get; set; }
        public bool boolFICASSCCExempt { get; set; }
    }
}
