//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.AdminPanel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPayrollImportFileTemplateDetail
    {
        public int intTemplateDetailId { get; set; }
        public Nullable<int> intTemplateId { get; set; }
        public Nullable<int> intFieldIndex { get; set; }
        public string sFieldName { get; set; }
        public string sFieldNameAsValue { get; set; }
        public string sFieldMapping { get; set; }
        public string sMappingTable { get; set; }
        public string sMappingColumn { get; set; }
        public string sColumnDataType { get; set; }
        public Nullable<System.DateTime> dtCreationDate { get; set; }
    
        public virtual tblPayrollImportFileTemplate tblPayrollImportFileTemplate { get; set; }
    }
}
