//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.AdminPanel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserBatchCompensation
    {
        public System.Guid strBatchID { get; set; }
        public int intUserID { get; set; }
        public string strCompensationName { get; set; }
        public decimal decPayRate { get; set; }
        public System.DateTime dtPayDate { get; set; }
        public decimal decHours { get; set; }
        public decimal decPay { get; set; }
        public System.DateTime dtTimeStamp { get; set; }
        public string strGLAccount { get; set; }
        public bool boolDeleted { get; set; }
        public int intSequenceNumber { get; set; }
        public int intEditType { get; set; }
        public int intUBMESequence { get; set; }
    }
}
