//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.AdminPanel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUserBatch
    {
        public int intUserID { get; set; }
        public string strBatchID { get; set; }
        public int intPayWeekNum { get; set; }
        public int intUserBatchStatus { get; set; }
        public System.DateTime dtStartDatePeriod { get; set; }
        public System.DateTime dtEndDatePeriod { get; set; }
        public Nullable<int> intCompanyID { get; set; }
        public Nullable<int> intDepartmentID { get; set; }
        public Nullable<int> intSubdepartmentID { get; set; }
        public Nullable<int> intEmployeeTypeID { get; set; }
        public int intPayMethodType { get; set; }
    }
}
