//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.AdminPanel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWithholdingsItem
    {
        public string strWithHoldingsName { get; set; }
        public string strDescription { get; set; }
        public int intPrePostTaxDeduction { get; set; }
        public int intComputationType { get; set; }
        public decimal decEmployeePercent { get; set; }
        public decimal decEmployeeAmount { get; set; }
        public decimal decCompanyPercent { get; set; }
        public decimal decCompanyAmount { get; set; }
        public decimal decMaximumSalaryLimit { get; set; }
        public decimal decMinimumSalaryLimit { get; set; }
        public bool boolDeleted { get; set; }
        public Nullable<int> intWithholdingsTaxType { get; set; }
        public string strGLAccount { get; set; }
        public string strContributionsName { get; set; }
        public string strGLAccount_Contributions { get; set; }
        public bool boolIsLoan { get; set; }
        public bool boolIs401kPlan { get; set; }
        public bool boolUserWithholding { get; set; }
        public bool boolCompanyContribution { get; set; }
        public string strGLContributionPayable { get; set; }
    }
}
