//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.AdminPanel.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPay_UserRecord
    {
        public int intUserID { get; set; }
        public string strCompanyName { get; set; }
        public int intPayrollUserStatus { get; set; }
        public string strStatusName { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string idno { get; set; }
        public Nullable<int> nStatus { get; set; }
        public string sNotes { get; set; }
        public string sCompanyName { get; set; }
        public string sDeptName { get; set; }
        public string sJobTitleName { get; set; }
        public string sEmployeeTypeName { get; set; }
        public string sPayrollRuleName { get; set; }
        public string sScheduleName { get; set; }
        public Nullable<int> nDeptID { get; set; }
        public Nullable<int> nJobTitleID { get; set; }
        public Nullable<int> nGroupID { get; set; }
        public Nullable<int> nEmployeeType { get; set; }
        public Nullable<int> nCompanyID { get; set; }
        public Nullable<int> nPayrollRuleID { get; set; }
        public Nullable<int> nScheduleID { get; set; }
        public Nullable<System.DateTime> dCompanySeniorityDate { get; set; }
        public string sSSN { get; set; }
        public string sHomeAddressLine1 { get; set; }
        public string sHomeAddressLine2 { get; set; }
        public string sHomeCity { get; set; }
        public string sHomeState { get; set; }
        public string sHomeZipCode { get; set; }
        public string sHomePhoneHum { get; set; }
        public string sSex { get; set; }
        public string sMaritalStatus { get; set; }
        public Nullable<System.DateTime> dBirthDate { get; set; }
        public Nullable<System.DateTime> dOriginalHiredDate { get; set; }
        public Nullable<double> dblHourlyRate { get; set; }
        public string sRegTempCode { get; set; }
        public string sFullPartTimeCode { get; set; }
        public Nullable<double> dblBaseCompensationRate { get; set; }
        public string email { get; set; }
        public string strEIN { get; set; }
        public int intPositionID { get; set; }
        public string strPositionName { get; set; }
        public Nullable<System.DateTime> dTerminationDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string FirstLastName { get; set; }
        public string SecondLastName { get; set; }
    }
}
