//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TimeAide.Web.WebPunchEmployeeLoginService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsEmployeeLoginSoap", Namespace="http://cloudaide.timeaide.com/wsEmployeeLogin")]
    public partial class wsEmployeeLogin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EmployeeLoginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsEmployeeLogin() {
            this.Url = global::TimeAide.Web.Properties.Settings.Default.TimeAide_Web_WebPunchEmployeeLoginService_wsEmployeeLogin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EmployeeLoginCompletedEventHandler EmployeeLoginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsEmployeeLogin/EmployeeLogin", RequestNamespace="http://cloudaide.timeaide.com/wsEmployeeLogin", ResponseNamespace="http://cloudaide.timeaide.com/wsEmployeeLogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsEmployeeLoginResult EmployeeLogin(string strSessionToken, string intEmployeeID, string strPassword) {
            object[] results = this.Invoke("EmployeeLogin", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        strPassword});
            return ((clsEmployeeLoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void EmployeeLoginAsync(string strSessionToken, string intEmployeeID, string strPassword) {
            this.EmployeeLoginAsync(strSessionToken, intEmployeeID, strPassword, null);
        }
        
        /// <remarks/>
        public void EmployeeLoginAsync(string strSessionToken, string intEmployeeID, string strPassword, object userState) {
            if ((this.EmployeeLoginOperationCompleted == null)) {
                this.EmployeeLoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeeLoginOperationCompleted);
            }
            this.InvokeAsync("EmployeeLogin", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        strPassword}, this.EmployeeLoginOperationCompleted, userState);
        }
        
        private void OnEmployeeLoginOperationCompleted(object arg) {
            if ((this.EmployeeLoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeeLoginCompleted(this, new EmployeeLoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsEmployeeLogin")]
    public partial class clsEmployeeLoginResult {
        
        private int intTokenValidationResultField;
        
        private SessionTokenValidationResult strTokenValidationResultField;
        
        private int intEmployeeLoginResultField;
        
        private enumEmployeeLoginResult strEmployeeLoginResultField;
        
        private clsUserInfoItem clsUserInfoRecordField;
        
        private string[] lstUserAlertsField;
        
        /// <remarks/>
        public int intTokenValidationResult {
            get {
                return this.intTokenValidationResultField;
            }
            set {
                this.intTokenValidationResultField = value;
            }
        }
        
        /// <remarks/>
        public SessionTokenValidationResult strTokenValidationResult {
            get {
                return this.strTokenValidationResultField;
            }
            set {
                this.strTokenValidationResultField = value;
            }
        }
        
        /// <remarks/>
        public int intEmployeeLoginResult {
            get {
                return this.intEmployeeLoginResultField;
            }
            set {
                this.intEmployeeLoginResultField = value;
            }
        }
        
        /// <remarks/>
        public enumEmployeeLoginResult strEmployeeLoginResult {
            get {
                return this.strEmployeeLoginResultField;
            }
            set {
                this.strEmployeeLoginResultField = value;
            }
        }
        
        /// <remarks/>
        public clsUserInfoItem clsUserInfoRecord {
            get {
                return this.clsUserInfoRecordField;
            }
            set {
                this.clsUserInfoRecordField = value;
            }
        }
        
        /// <remarks/>
        public string[] lstUserAlerts {
            get {
                return this.lstUserAlertsField;
            }
            set {
                this.lstUserAlertsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsEmployeeLogin")]
    public enum SessionTokenValidationResult {
        
        /// <remarks/>
        MiscError,
        
        /// <remarks/>
        TokenIsValid,
        
        /// <remarks/>
        IsEmpty,
        
        /// <remarks/>
        InvalidFormat,
        
        /// <remarks/>
        NotFoundInDB,
        
        /// <remarks/>
        Expired,
        
        /// <remarks/>
        ConsumationCountExceeded,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsEmployeeLogin")]
    public enum enumEmployeeLoginResult {
        
        /// <remarks/>
        General_Error,
        
        /// <remarks/>
        Validation_Successful,
        
        /// <remarks/>
        Validation_Failed,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsEmployeeLogin")]
    public partial class clsUserInfoItem {
        
        private string userIDField;
        
        private string userFullNameField;
        
        private string userCompanyField;
        
        private string userDepartmentField;
        
        private string userSubDepartmentField;
        
        private string userEmployeeTypeField;
        
        /// <remarks/>
        public string UserID {
            get {
                return this.userIDField;
            }
            set {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        public string UserFullName {
            get {
                return this.userFullNameField;
            }
            set {
                this.userFullNameField = value;
            }
        }
        
        /// <remarks/>
        public string UserCompany {
            get {
                return this.userCompanyField;
            }
            set {
                this.userCompanyField = value;
            }
        }
        
        /// <remarks/>
        public string UserDepartment {
            get {
                return this.userDepartmentField;
            }
            set {
                this.userDepartmentField = value;
            }
        }
        
        /// <remarks/>
        public string UserSubDepartment {
            get {
                return this.userSubDepartmentField;
            }
            set {
                this.userSubDepartmentField = value;
            }
        }
        
        /// <remarks/>
        public string UserEmployeeType {
            get {
                return this.userEmployeeTypeField;
            }
            set {
                this.userEmployeeTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void EmployeeLoginCompletedEventHandler(object sender, EmployeeLoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmployeeLoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmployeeLoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsEmployeeLoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsEmployeeLoginResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591