//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TimeAide.Web.WebPunchComputeService2 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsComputeTimeSheetSoap", Namespace="http://cloudaide.timeaide.com/wsComputeTimeSheet/")]
    public partial class wsComputeTimeSheet : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ComputeEventOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsComputeTimeSheet() {
            this.Url = global::TimeAide.Web.Properties.Settings.Default.TimeAide_Web_WebPunchComputeService2_wsComputeTimeSheet;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ComputeEventCompletedEventHandler ComputeEventCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsComputeTimeSheet/ComputeEvent", RequestNamespace="http://cloudaide.timeaide.com/wsComputeTimeSheet/", ResponseNamespace="http://cloudaide.timeaide.com/wsComputeTimeSheet/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsComputeEventResult ComputeEvent(string strSessionToken, string intEventUserID, string dtEventStartDate, string dtEventEndDate) {
            object[] results = this.Invoke("ComputeEvent", new object[] {
                        strSessionToken,
                        intEventUserID,
                        dtEventStartDate,
                        dtEventEndDate});
            return ((clsComputeEventResult)(results[0]));
        }
        
        /// <remarks/>
        public void ComputeEventAsync(string strSessionToken, string intEventUserID, string dtEventStartDate, string dtEventEndDate) {
            this.ComputeEventAsync(strSessionToken, intEventUserID, dtEventStartDate, dtEventEndDate, null);
        }
        
        /// <remarks/>
        public void ComputeEventAsync(string strSessionToken, string intEventUserID, string dtEventStartDate, string dtEventEndDate, object userState) {
            if ((this.ComputeEventOperationCompleted == null)) {
                this.ComputeEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnComputeEventOperationCompleted);
            }
            this.InvokeAsync("ComputeEvent", new object[] {
                        strSessionToken,
                        intEventUserID,
                        dtEventStartDate,
                        dtEventEndDate}, this.ComputeEventOperationCompleted, userState);
        }
        
        private void OnComputeEventOperationCompleted(object arg) {
            if ((this.ComputeEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ComputeEventCompleted(this, new ComputeEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsComputeTimeSheet/")]
    public partial class clsComputeEventResult {
        
        private int intTokenValidationResultField;
        
        private SessionTokenValidationResult strTokenValidationResultField;
        
        private int intComputeEventResultField;
        
        private enumComputeEventResult strComputeEventResultField;
        
        /// <remarks/>
        public int intTokenValidationResult {
            get {
                return this.intTokenValidationResultField;
            }
            set {
                this.intTokenValidationResultField = value;
            }
        }
        
        /// <remarks/>
        public SessionTokenValidationResult strTokenValidationResult {
            get {
                return this.strTokenValidationResultField;
            }
            set {
                this.strTokenValidationResultField = value;
            }
        }
        
        /// <remarks/>
        public int intComputeEventResult {
            get {
                return this.intComputeEventResultField;
            }
            set {
                this.intComputeEventResultField = value;
            }
        }
        
        /// <remarks/>
        public enumComputeEventResult strComputeEventResult {
            get {
                return this.strComputeEventResultField;
            }
            set {
                this.strComputeEventResultField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsComputeTimeSheet/")]
    public enum SessionTokenValidationResult {
        
        /// <remarks/>
        MiscError,
        
        /// <remarks/>
        TokenIsValid,
        
        /// <remarks/>
        IsEmpty,
        
        /// <remarks/>
        InvalidFormat,
        
        /// <remarks/>
        NotFoundInDB,
        
        /// <remarks/>
        Expired,
        
        /// <remarks/>
        ConsumationCountExceeded,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsComputeTimeSheet/")]
    public enum enumComputeEventResult {
        
        /// <remarks/>
        Misc_Error,
        
        /// <remarks/>
        Compute_Successful,
        
        /// <remarks/>
        Error_Saving_In_DB,
        
        /// <remarks/>
        EmployeeID_Empty,
        
        /// <remarks/>
        EmployeeID_Invalid_Format,
        
        /// <remarks/>
        EventDate_Empty,
        
        /// <remarks/>
        EventDate_Invalid_Format,
        
        /// <remarks/>
        EventTime_Empty,
        
        /// <remarks/>
        EventTime_Invalid_Format,
        
        /// <remarks/>
        EventResult_Empty,
        
        /// <remarks/>
        EventResult_Invalid_Format,
        
        /// <remarks/>
        EventTerminalID_Empty,
        
        /// <remarks/>
        EventTerminalID_Invalid_Format,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ComputeEventCompletedEventHandler(object sender, ComputeEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ComputeEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ComputeEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsComputeEventResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsComputeEventResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591