//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TimeAide.Web.WebPunchLoginService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsLoginSoap", Namespace="http://cloudaide.timeaide.com/wsLogin")]
    public partial class wsLogin : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoginOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginWithCCOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsLogin() {
            this.Url = global::TimeAide.Web.Properties.Settings.Default.TimeAide_Web_WebPunchLoginService_wsLogin;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoginCompletedEventHandler LoginCompleted;
        
        /// <remarks/>
        public event LoginWithCCCompletedEventHandler LoginWithCCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsLogin/Login", RequestNamespace="http://cloudaide.timeaide.com/wsLogin", ResponseNamespace="http://cloudaide.timeaide.com/wsLogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsLoginResult Login(string strAPIKey, string strPassword) {
            object[] results = this.Invoke("Login", new object[] {
                        strAPIKey,
                        strPassword});
            return ((clsLoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void LoginAsync(string strAPIKey, string strPassword) {
            this.LoginAsync(strAPIKey, strPassword, null);
        }
        
        /// <remarks/>
        public void LoginAsync(string strAPIKey, string strPassword, object userState) {
            if ((this.LoginOperationCompleted == null)) {
                this.LoginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginOperationCompleted);
            }
            this.InvokeAsync("Login", new object[] {
                        strAPIKey,
                        strPassword}, this.LoginOperationCompleted, userState);
        }
        
        private void OnLoginOperationCompleted(object arg) {
            if ((this.LoginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginCompleted(this, new LoginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsLogin/LoginWithCC", RequestNamespace="http://cloudaide.timeaide.com/wsLogin", ResponseNamespace="http://cloudaide.timeaide.com/wsLogin", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsLoginResult LoginWithCC(string strAPIKey, string strPassword, string strCompanyCode) {
            object[] results = this.Invoke("LoginWithCC", new object[] {
                        strAPIKey,
                        strPassword,
                        strCompanyCode});
            return ((clsLoginResult)(results[0]));
        }
        
        /// <remarks/>
        public void LoginWithCCAsync(string strAPIKey, string strPassword, string strCompanyCode) {
            this.LoginWithCCAsync(strAPIKey, strPassword, strCompanyCode, null);
        }
        
        /// <remarks/>
        public void LoginWithCCAsync(string strAPIKey, string strPassword, string strCompanyCode, object userState) {
            if ((this.LoginWithCCOperationCompleted == null)) {
                this.LoginWithCCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginWithCCOperationCompleted);
            }
            this.InvokeAsync("LoginWithCC", new object[] {
                        strAPIKey,
                        strPassword,
                        strCompanyCode}, this.LoginWithCCOperationCompleted, userState);
        }
        
        private void OnLoginWithCCOperationCompleted(object arg) {
            if ((this.LoginWithCCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginWithCCCompleted(this, new LoginWithCCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsLogin")]
    public partial class clsLoginResult {
        
        private int intLoginResultField;
        
        private enumLoginResult strLoginResultField;
        
        private string strSessionTokenField;
        
        /// <remarks/>
        public int intLoginResult {
            get {
                return this.intLoginResultField;
            }
            set {
                this.intLoginResultField = value;
            }
        }
        
        /// <remarks/>
        public enumLoginResult strLoginResult {
            get {
                return this.strLoginResultField;
            }
            set {
                this.strLoginResultField = value;
            }
        }
        
        /// <remarks/>
        public string strSessionToken {
            get {
                return this.strSessionTokenField;
            }
            set {
                this.strSessionTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsLogin")]
    public enum enumLoginResult {
        
        /// <remarks/>
        General_Error,
        
        /// <remarks/>
        Password_Match,
        
        /// <remarks/>
        Password_Matching_Failed,
        
        /// <remarks/>
        APIKey_or_Password_IsEmpty,
        
        /// <remarks/>
        SessionToken_Generation_Failed,
        
        /// <remarks/>
        SessionToken_Not_Saved_in_DB,
        
        /// <remarks/>
        APIKey_Not_Found,
        
        /// <remarks/>
        Password_Not_Found_For_APIKey,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginCompletedEventHandler(object sender, LoginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsLoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsLoginResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void LoginWithCCCompletedEventHandler(object sender, LoginWithCCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginWithCCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginWithCCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsLoginResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsLoginResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591