//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TimeAide.Web.WebPunchValidateEventService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsValidateEventSoap", Namespace="http://cloudaide.timeaide.com/wsValidateEvent")]
    public partial class wsValidateEvent : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ValidateEventOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateEvent_GPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateEvent_PWDOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateEvent_PWD_GPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateEventWithGPSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidateEvent_GPS_JCOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsValidateEvent() {
            this.Url = global::TimeAide.Web.Properties.Settings.Default.TimeAide_Web_WebPunchValidateEventService_wsValidateEvent;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ValidateEventCompletedEventHandler ValidateEventCompleted;
        
        /// <remarks/>
        public event ValidateEvent_GPSCompletedEventHandler ValidateEvent_GPSCompleted;
        
        /// <remarks/>
        public event ValidateEvent_PWDCompletedEventHandler ValidateEvent_PWDCompleted;
        
        /// <remarks/>
        public event ValidateEvent_PWD_GPSCompletedEventHandler ValidateEvent_PWD_GPSCompleted;
        
        /// <remarks/>
        public event ValidateEventWithGPSCompletedEventHandler ValidateEventWithGPSCompleted;
        
        /// <remarks/>
        public event ValidateEvent_GPS_JCCompletedEventHandler ValidateEvent_GPS_JCCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsValidateEvent/ValidateEvent", RequestNamespace="http://cloudaide.timeaide.com/wsValidateEvent", ResponseNamespace="http://cloudaide.timeaide.com/wsValidateEvent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsValidateEventResult ValidateEvent(string strSessionToken, string intEmployeeID, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode) {
            object[] results = this.Invoke("ValidateEvent", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        dtEventDate,
                        dtEventTime,
                        intEventMode,
                        intJobCode});
            return ((clsValidateEventResult)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateEventAsync(string strSessionToken, string intEmployeeID, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode) {
            this.ValidateEventAsync(strSessionToken, intEmployeeID, dtEventDate, dtEventTime, intEventMode, intJobCode, null);
        }
        
        /// <remarks/>
        public void ValidateEventAsync(string strSessionToken, string intEmployeeID, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode, object userState) {
            if ((this.ValidateEventOperationCompleted == null)) {
                this.ValidateEventOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateEventOperationCompleted);
            }
            this.InvokeAsync("ValidateEvent", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        dtEventDate,
                        dtEventTime,
                        intEventMode,
                        intJobCode}, this.ValidateEventOperationCompleted, userState);
        }
        
        private void OnValidateEventOperationCompleted(object arg) {
            if ((this.ValidateEventCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateEventCompleted(this, new ValidateEventCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsValidateEvent/ValidateEvent_GPS", RequestNamespace="http://cloudaide.timeaide.com/wsValidateEvent", ResponseNamespace="http://cloudaide.timeaide.com/wsValidateEvent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsValidateEventResult ValidateEvent_GPS(string strSessionToken, string intEmployeeID, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode, string decLatitude, string decLongitude, string intGPS_Exception) {
            object[] results = this.Invoke("ValidateEvent_GPS", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        dtEventDate,
                        dtEventTime,
                        intEventMode,
                        intJobCode,
                        decLatitude,
                        decLongitude,
                        intGPS_Exception});
            return ((clsValidateEventResult)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateEvent_GPSAsync(string strSessionToken, string intEmployeeID, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode, string decLatitude, string decLongitude, string intGPS_Exception) {
            this.ValidateEvent_GPSAsync(strSessionToken, intEmployeeID, dtEventDate, dtEventTime, intEventMode, intJobCode, decLatitude, decLongitude, intGPS_Exception, null);
        }
        
        /// <remarks/>
        public void ValidateEvent_GPSAsync(string strSessionToken, string intEmployeeID, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode, string decLatitude, string decLongitude, string intGPS_Exception, object userState) {
            if ((this.ValidateEvent_GPSOperationCompleted == null)) {
                this.ValidateEvent_GPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateEvent_GPSOperationCompleted);
            }
            this.InvokeAsync("ValidateEvent_GPS", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        dtEventDate,
                        dtEventTime,
                        intEventMode,
                        intJobCode,
                        decLatitude,
                        decLongitude,
                        intGPS_Exception}, this.ValidateEvent_GPSOperationCompleted, userState);
        }
        
        private void OnValidateEvent_GPSOperationCompleted(object arg) {
            if ((this.ValidateEvent_GPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateEvent_GPSCompleted(this, new ValidateEvent_GPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsValidateEvent/ValidateEvent_PWD", RequestNamespace="http://cloudaide.timeaide.com/wsValidateEvent", ResponseNamespace="http://cloudaide.timeaide.com/wsValidateEvent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsValidateEventResult ValidateEvent_PWD(string strSessionToken, string intEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode) {
            object[] results = this.Invoke("ValidateEvent_PWD", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        strPassword,
                        dtEventDate,
                        dtEventTime,
                        intEventMode,
                        intJobCode});
            return ((clsValidateEventResult)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateEvent_PWDAsync(string strSessionToken, string intEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode) {
            this.ValidateEvent_PWDAsync(strSessionToken, intEmployeeID, strPassword, dtEventDate, dtEventTime, intEventMode, intJobCode, null);
        }
        
        /// <remarks/>
        public void ValidateEvent_PWDAsync(string strSessionToken, string intEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode, object userState) {
            if ((this.ValidateEvent_PWDOperationCompleted == null)) {
                this.ValidateEvent_PWDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateEvent_PWDOperationCompleted);
            }
            this.InvokeAsync("ValidateEvent_PWD", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        strPassword,
                        dtEventDate,
                        dtEventTime,
                        intEventMode,
                        intJobCode}, this.ValidateEvent_PWDOperationCompleted, userState);
        }
        
        private void OnValidateEvent_PWDOperationCompleted(object arg) {
            if ((this.ValidateEvent_PWDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateEvent_PWDCompleted(this, new ValidateEvent_PWDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsValidateEvent/ValidateEvent_PWD_GPS", RequestNamespace="http://cloudaide.timeaide.com/wsValidateEvent", ResponseNamespace="http://cloudaide.timeaide.com/wsValidateEvent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsValidateEventResult ValidateEvent_PWD_GPS(string strSessionToken, string intEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode, string decLatitude, string decLongitude, string intGPS_Exception) {
            object[] results = this.Invoke("ValidateEvent_PWD_GPS", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        strPassword,
                        dtEventDate,
                        dtEventTime,
                        intEventMode,
                        intJobCode,
                        decLatitude,
                        decLongitude,
                        intGPS_Exception});
            return ((clsValidateEventResult)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateEvent_PWD_GPSAsync(string strSessionToken, string intEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode, string decLatitude, string decLongitude, string intGPS_Exception) {
            this.ValidateEvent_PWD_GPSAsync(strSessionToken, intEmployeeID, strPassword, dtEventDate, dtEventTime, intEventMode, intJobCode, decLatitude, decLongitude, intGPS_Exception, null);
        }
        
        /// <remarks/>
        public void ValidateEvent_PWD_GPSAsync(string strSessionToken, string intEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string intEventMode, string intJobCode, string decLatitude, string decLongitude, string intGPS_Exception, object userState) {
            if ((this.ValidateEvent_PWD_GPSOperationCompleted == null)) {
                this.ValidateEvent_PWD_GPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateEvent_PWD_GPSOperationCompleted);
            }
            this.InvokeAsync("ValidateEvent_PWD_GPS", new object[] {
                        strSessionToken,
                        intEmployeeID,
                        strPassword,
                        dtEventDate,
                        dtEventTime,
                        intEventMode,
                        intJobCode,
                        decLatitude,
                        decLongitude,
                        intGPS_Exception}, this.ValidateEvent_PWD_GPSOperationCompleted, userState);
        }
        
        private void OnValidateEvent_PWD_GPSOperationCompleted(object arg) {
            if ((this.ValidateEvent_PWD_GPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateEvent_PWD_GPSCompleted(this, new ValidateEvent_PWD_GPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsValidateEvent/ValidateEventWithGPS", RequestNamespace="http://cloudaide.timeaide.com/wsValidateEvent", ResponseNamespace="http://cloudaide.timeaide.com/wsValidateEvent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsValidateEventResult ValidateEventWithGPS(string strSessionToken, string intEventEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string intTerminalID, string decLatitude, string decLongitude) {
            object[] results = this.Invoke("ValidateEventWithGPS", new object[] {
                        strSessionToken,
                        intEventEmployeeID,
                        strPassword,
                        dtEventDate,
                        dtEventTime,
                        intTerminalID,
                        decLatitude,
                        decLongitude});
            return ((clsValidateEventResult)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateEventWithGPSAsync(string strSessionToken, string intEventEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string intTerminalID, string decLatitude, string decLongitude) {
            this.ValidateEventWithGPSAsync(strSessionToken, intEventEmployeeID, strPassword, dtEventDate, dtEventTime, intTerminalID, decLatitude, decLongitude, null);
        }
        
        /// <remarks/>
        public void ValidateEventWithGPSAsync(string strSessionToken, string intEventEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string intTerminalID, string decLatitude, string decLongitude, object userState) {
            if ((this.ValidateEventWithGPSOperationCompleted == null)) {
                this.ValidateEventWithGPSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateEventWithGPSOperationCompleted);
            }
            this.InvokeAsync("ValidateEventWithGPS", new object[] {
                        strSessionToken,
                        intEventEmployeeID,
                        strPassword,
                        dtEventDate,
                        dtEventTime,
                        intTerminalID,
                        decLatitude,
                        decLongitude}, this.ValidateEventWithGPSOperationCompleted, userState);
        }
        
        private void OnValidateEventWithGPSOperationCompleted(object arg) {
            if ((this.ValidateEventWithGPSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateEventWithGPSCompleted(this, new ValidateEventWithGPSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsValidateEvent/ValidateEvent_GPS_JC", RequestNamespace="http://cloudaide.timeaide.com/wsValidateEvent", ResponseNamespace="http://cloudaide.timeaide.com/wsValidateEvent", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsValidateEventResult ValidateEvent_GPS_JC(string strSessionToken, string intEventEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string decLatitude, string decLongitude, string intJobCodeID) {
            object[] results = this.Invoke("ValidateEvent_GPS_JC", new object[] {
                        strSessionToken,
                        intEventEmployeeID,
                        strPassword,
                        dtEventDate,
                        dtEventTime,
                        decLatitude,
                        decLongitude,
                        intJobCodeID});
            return ((clsValidateEventResult)(results[0]));
        }
        
        /// <remarks/>
        public void ValidateEvent_GPS_JCAsync(string strSessionToken, string intEventEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string decLatitude, string decLongitude, string intJobCodeID) {
            this.ValidateEvent_GPS_JCAsync(strSessionToken, intEventEmployeeID, strPassword, dtEventDate, dtEventTime, decLatitude, decLongitude, intJobCodeID, null);
        }
        
        /// <remarks/>
        public void ValidateEvent_GPS_JCAsync(string strSessionToken, string intEventEmployeeID, string strPassword, string dtEventDate, string dtEventTime, string decLatitude, string decLongitude, string intJobCodeID, object userState) {
            if ((this.ValidateEvent_GPS_JCOperationCompleted == null)) {
                this.ValidateEvent_GPS_JCOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidateEvent_GPS_JCOperationCompleted);
            }
            this.InvokeAsync("ValidateEvent_GPS_JC", new object[] {
                        strSessionToken,
                        intEventEmployeeID,
                        strPassword,
                        dtEventDate,
                        dtEventTime,
                        decLatitude,
                        decLongitude,
                        intJobCodeID}, this.ValidateEvent_GPS_JCOperationCompleted, userState);
        }
        
        private void OnValidateEvent_GPS_JCOperationCompleted(object arg) {
            if ((this.ValidateEvent_GPS_JCCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidateEvent_GPS_JCCompleted(this, new ValidateEvent_GPS_JCCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsValidateEvent")]
    public partial class clsValidateEventResult {
        
        private int intTokenValidationResultField;
        
        private SessionTokenValidationResult strTokenValidationResultField;
        
        private int intValidateEventResultField;
        
        private enumValidateEventResult strValidateEventResultField;
        
        private string strReturnMessageField;
        
        /// <remarks/>
        public int intTokenValidationResult {
            get {
                return this.intTokenValidationResultField;
            }
            set {
                this.intTokenValidationResultField = value;
            }
        }
        
        /// <remarks/>
        public SessionTokenValidationResult strTokenValidationResult {
            get {
                return this.strTokenValidationResultField;
            }
            set {
                this.strTokenValidationResultField = value;
            }
        }
        
        /// <remarks/>
        public int intValidateEventResult {
            get {
                return this.intValidateEventResultField;
            }
            set {
                this.intValidateEventResultField = value;
            }
        }
        
        /// <remarks/>
        public enumValidateEventResult strValidateEventResult {
            get {
                return this.strValidateEventResultField;
            }
            set {
                this.strValidateEventResultField = value;
            }
        }
        
        /// <remarks/>
        public string strReturnMessage {
            get {
                return this.strReturnMessageField;
            }
            set {
                this.strReturnMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsValidateEvent")]
    public enum SessionTokenValidationResult {
        
        /// <remarks/>
        MiscError,
        
        /// <remarks/>
        TokenIsValid,
        
        /// <remarks/>
        IsEmpty,
        
        /// <remarks/>
        InvalidFormat,
        
        /// <remarks/>
        NotFoundInDB,
        
        /// <remarks/>
        Expired,
        
        /// <remarks/>
        ConsumationCountExceeded,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsValidateEvent")]
    public enum enumValidateEventResult {
        
        /// <remarks/>
        General_Error,
        
        /// <remarks/>
        Pending_Validation,
        
        /// <remarks/>
        Validation_Successful,
        
        /// <remarks/>
        Password_Matching_Failed,
        
        /// <remarks/>
        GeoTerminal_Disabled_For_Employee,
        
        /// <remarks/>
        Database_No_Employee_Found,
        
        /// <remarks/>
        Database_No_Password_In_UserRecord,
        
        /// <remarks/>
        Database_No_GeoTerminal_Assigned,
        
        /// <remarks/>
        Database_Error_Saving_In_tEnter,
        
        /// <remarks/>
        Restriction_GeoTerminal,
        
        /// <remarks/>
        Restriction_TimeRestriction,
        
        /// <remarks/>
        EmployeeID_Empty,
        
        /// <remarks/>
        EmployeeID_Invalid_Format,
        
        /// <remarks/>
        Password_Empty,
        
        /// <remarks/>
        EventDate_Empty,
        
        /// <remarks/>
        EventDate_Invalid_Format,
        
        /// <remarks/>
        EventTime_Empty,
        
        /// <remarks/>
        EventTime_Invalid_Format,
        
        /// <remarks/>
        TerminalID_Empty,
        
        /// <remarks/>
        TerminalID_Invalid_Format,
        
        /// <remarks/>
        Latitude_Empty,
        
        /// <remarks/>
        Longitude_Empty,
        
        /// <remarks/>
        Latitude_Invalid_Format,
        
        /// <remarks/>
        Longitude_Invalid_Format,
        
        /// <remarks/>
        JobCode_Empty,
        
        /// <remarks/>
        JobCode_Invalid_Format,
        
        /// <remarks/>
        JobCode_Not_Found,
        
        /// <remarks/>
        EventMode_Empty,
        
        /// <remarks/>
        EventMode_Invalid_Format,
        
        /// <remarks/>
        GeoLocation_Error,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateEventCompletedEventHandler(object sender, ValidateEventCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateEventCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateEventCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsValidateEventResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsValidateEventResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateEvent_GPSCompletedEventHandler(object sender, ValidateEvent_GPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateEvent_GPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateEvent_GPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsValidateEventResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsValidateEventResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateEvent_PWDCompletedEventHandler(object sender, ValidateEvent_PWDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateEvent_PWDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateEvent_PWDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsValidateEventResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsValidateEventResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateEvent_PWD_GPSCompletedEventHandler(object sender, ValidateEvent_PWD_GPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateEvent_PWD_GPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateEvent_PWD_GPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsValidateEventResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsValidateEventResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateEventWithGPSCompletedEventHandler(object sender, ValidateEventWithGPSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateEventWithGPSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateEventWithGPSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsValidateEventResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsValidateEventResult)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ValidateEvent_GPS_JCCompletedEventHandler(object sender, ValidateEvent_GPS_JCCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidateEvent_GPS_JCCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidateEvent_GPS_JCCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsValidateEventResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsValidateEventResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591