//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TimeAide.Web.WebPunchSessionTokenService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsGetSessionTokenSoap", Namespace="http://cloudaide.timeaide.com/wsGetSessionToken")]
    public partial class wsGetSessionToken : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetSessionTokenOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public wsGetSessionToken() {
            this.Url = global::TimeAide.Web.Properties.Settings.Default.TimeAide_Web_WebPunchSessionTokenService_wsGetSessionToken;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetSessionTokenCompletedEventHandler GetSessionTokenCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://cloudaide.timeaide.com/wsGetSessionToken/GetSessionToken", RequestNamespace="http://cloudaide.timeaide.com/wsGetSessionToken", ResponseNamespace="http://cloudaide.timeaide.com/wsGetSessionToken", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public clsGetSessionTokenResult GetSessionToken(string strAPIKey, string strPassword, string strCompanyCode) {
            object[] results = this.Invoke("GetSessionToken", new object[] {
                        strAPIKey,
                        strPassword,
                        strCompanyCode});
            return ((clsGetSessionTokenResult)(results[0]));
        }
        
        /// <remarks/>
        public void GetSessionTokenAsync(string strAPIKey, string strPassword, string strCompanyCode) {
            this.GetSessionTokenAsync(strAPIKey, strPassword, strCompanyCode, null);
        }
        
        /// <remarks/>
        public void GetSessionTokenAsync(string strAPIKey, string strPassword, string strCompanyCode, object userState) {
            if ((this.GetSessionTokenOperationCompleted == null)) {
                this.GetSessionTokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSessionTokenOperationCompleted);
            }
            this.InvokeAsync("GetSessionToken", new object[] {
                        strAPIKey,
                        strPassword,
                        strCompanyCode}, this.GetSessionTokenOperationCompleted, userState);
        }
        
        private void OnGetSessionTokenOperationCompleted(object arg) {
            if ((this.GetSessionTokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSessionTokenCompleted(this, new GetSessionTokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsGetSessionToken")]
    public partial class clsGetSessionTokenResult {
        
        private int intGetSessionTokenResultField;
        
        private enumGetSessionTokenResult strGetSessionTokenResultField;
        
        private string strSessionTokenField;
        
        /// <remarks/>
        public int intGetSessionTokenResult {
            get {
                return this.intGetSessionTokenResultField;
            }
            set {
                this.intGetSessionTokenResultField = value;
            }
        }
        
        /// <remarks/>
        public enumGetSessionTokenResult strGetSessionTokenResult {
            get {
                return this.strGetSessionTokenResultField;
            }
            set {
                this.strGetSessionTokenResultField = value;
            }
        }
        
        /// <remarks/>
        public string strSessionToken {
            get {
                return this.strSessionTokenField;
            }
            set {
                this.strSessionTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://cloudaide.timeaide.com/wsGetSessionToken")]
    public enum enumGetSessionTokenResult {
        
        /// <remarks/>
        General_Error,
        
        /// <remarks/>
        Password_Match,
        
        /// <remarks/>
        Password_Matching_Failed,
        
        /// <remarks/>
        APIKey_or_Password_or_Customer_IsEmpty,
        
        /// <remarks/>
        SessionToken_Generation_Failed,
        
        /// <remarks/>
        SessionToken_Not_Saved_in_DB,
        
        /// <remarks/>
        APIKey_Not_Found,
        
        /// <remarks/>
        Password_Not_Found_For_APIKey,
        
        /// <remarks/>
        Customer_Not_Found,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetSessionTokenCompletedEventHandler(object sender, GetSessionTokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSessionTokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSessionTokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public clsGetSessionTokenResult Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((clsGetSessionTokenResult)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591