--SELECT TABLE_NAME
--FROM INFORMATION_SCHEMA.TABLES
--WHERE TABLE_TYPE = 'BASE TABLE' --AND TABLE_CATALOG='dbName'

--Order by TABLE_NAME

SELECT COLUMN_NAME

FROM INFORMATION_SCHEMA.COLUMNS

WHERE TABLE_NAME = 'tblCompany'

ORDER BY ORDINAL_POSITION