//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCompanyPayrollInformation
    {
        public string strCompanyName { get; set; }
        public string strAddress1 { get; set; }
        public string strAddress2 { get; set; }
        public string strCity { get; set; }
        public string strState { get; set; }
        public string strZipCode { get; set; }
        public string strCountry { get; set; }
        public string strPhone { get; set; }
        public string strFax { get; set; }
        public string strEmail { get; set; }
        public string strWebSite { get; set; }
        public string strContactName { get; set; }
        public string strPayrollName { get; set; }
        public string strPayrollAddress1 { get; set; }
        public string strPayrollAddress2 { get; set; }
        public string strPayrollCountry { get; set; }
        public string strPayrollCity { get; set; }
        public string strPayrollState { get; set; }
        public string strPayrollZipCode { get; set; }
        public string strEIN { get; set; }
        public string strPayrollFax { get; set; }
        public string strPayrollContactName { get; set; }
        public string strPayrollContactTitle { get; set; }
        public string strPayrollContactPhone { get; set; }
        public string strPayrollEmail { get; set; }
        public Nullable<System.DateTime> dtCompanyStartDate { get; set; }
        public string strSICCode { get; set; }
        public string strNAICSCode { get; set; }
        public string strSeguroChoferilAccount { get; set; }
        public string strDepartamentoDelTrabajoAccount { get; set; }
        public decimal decDepartamentoDelTrabajoRate { get; set; }
    }
}
