//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSS_TimeOffRequest
    {
        public int intTORUniqueID { get; set; }
        public Nullable<int> intUserID { get; set; }
        public string strTransType { get; set; }
        public Nullable<bool> bitSingleDay { get; set; }
        public Nullable<System.DateTime> dtStartDate { get; set; }
        public Nullable<System.DateTime> dtEndDate { get; set; }
        public Nullable<System.DateTime> dtDayStart { get; set; }
        public Nullable<decimal> decDayHours { get; set; }
        public string strRequestNote { get; set; }
        public Nullable<int> intTORStatusID { get; set; }
        public System.DateTime dtTimestamp { get; set; }
        public string strCompanyName { get; set; }
    }
}
