//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTAEDetail
    {
        public int intTAEDetailID { get; set; }
        public string strBatchID { get; set; }
        public string strBatchDescription { get; set; }
        public int intUserID { get; set; }
        public string strUserName { get; set; }
        public string strCompensationName { get; set; }
        public Nullable<decimal> decPayRate { get; set; }
        public Nullable<decimal> decHours { get; set; }
        public Nullable<int> intEditType { get; set; }
        public System.DateTime dtPunchDate { get; set; }
        public decimal decPay { get; set; }
        public string strCompanyName { get; set; }
        public Nullable<int> intCompanyID { get; set; }
        public Nullable<int> intDepartmentID { get; set; }
        public Nullable<int> intSubdepartmentID { get; set; }
        public Nullable<int> intEmployeeType { get; set; }
        public string intTAESignID { get; set; }
    }
}
