//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TimeAideWindowContext : DbContext
    {
        public TimeAideWindowContext()
            : base("name=TimeAideWindowContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tCompany> tCompanies { get; set; }
        public virtual DbSet<tSchedModDailyDetail> tSchedModDailyDetails { get; set; }
        public virtual DbSet<tSchedModPeriodSumm> tSchedModPeriodSumms { get; set; }
        public virtual DbSet<tSchedule> tSchedules { get; set; }
        public virtual DbSet<tScheduleDayInfo> tScheduleDayInfoes { get; set; }
        public virtual DbSet<tuser> tusers { get; set; }
        public virtual DbSet<tAccrualType> tAccrualTypes { get; set; }
        public virtual DbSet<tPunchDate> tPunchDates { get; set; }
        public virtual DbSet<tReportWeek> tReportWeeks { get; set; }
        public virtual DbSet<viewPay_UserBatchStatus> viewPay_UserBatchStatus { get; set; }
        public virtual DbSet<tblCompanyPayrollInformation> tblCompanyPayrollInformations { get; set; }
        public virtual DbSet<tJobTitle> tJobTitle { get; set; }
        public virtual DbSet<tEmployeeType> tEmployeeType { get; set; }
        public virtual DbSet<tblSS_TransdefTimeOffRequest> tblSS_TransdefTimeOffRequest { get; set; }
        public virtual DbSet<tTransDef> tTransDef { get; set; }
        public virtual DbSet<tblSS_TimeOffRequest> tblSS_TimeOffRequest { get; set; }
        public virtual DbSet<tPunchData> tPunchData { get; set; }
        public virtual DbSet<tblSS_TransdefTimeOffDocument> tblSS_TransdefTimeOffDocument { get; set; }
        public virtual DbSet<tDept> tDept { get; set; }
        public virtual DbSet<tPunchPair> tPunchPair { get; set; }
        public virtual DbSet<tAuditInfo> tAuditInfo { get; set; }
        public virtual DbSet<tblTAEDetail> tblTAEDetail { get; set; }
        public virtual DbSet<tblTAESignature> tblTAESignature { get; set; }
    
        public virtual ObjectResult<spSS_CompensationBalances_Result> spSS_CompensationBalances(Nullable<int> userID, string accrualType, Nullable<System.DateTime> searchDate)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(int));
    
            var accrualTypeParameter = accrualType != null ?
                new ObjectParameter("AccrualType", accrualType) :
                new ObjectParameter("AccrualType", typeof(string));
    
            var searchDateParameter = searchDate.HasValue ?
                new ObjectParameter("SearchDate", searchDate) :
                new ObjectParameter("SearchDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSS_CompensationBalances_Result>("spSS_CompensationBalances", userIDParameter, accrualTypeParameter, searchDateParameter);
        }
    
        [DbFunction("TimeAideWindowContext", "fnPay_tblUserCompensationsYTD")]
        public virtual IQueryable<fnPay_tblUserCompensationsYTD_Result> fnPay_tblUserCompensationsYTD(string bATCHID)
        {
            var bATCHIDParameter = bATCHID != null ?
                new ObjectParameter("BATCHID", bATCHID) :
                new ObjectParameter("BATCHID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnPay_tblUserCompensationsYTD_Result>("[TimeAideWindowContext].[fnPay_tblUserCompensationsYTD](@BATCHID)", bATCHIDParameter);
        }
    
        [DbFunction("TimeAideWindowContext", "fnPay_tblUserWithholdingsYTD")]
        public virtual IQueryable<fnPay_tblUserWithholdingsYTD_Result> fnPay_tblUserWithholdingsYTD(string bATCHID)
        {
            var bATCHIDParameter = bATCHID != null ?
                new ObjectParameter("BATCHID", bATCHID) :
                new ObjectParameter("BATCHID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<fnPay_tblUserWithholdingsYTD_Result>("[TimeAideWindowContext].[fnPay_tblUserWithholdingsYTD](@BATCHID)", bATCHIDParameter);
        }
    
        public virtual int spSS_UpdateTimeOffRequestFromWeb(Nullable<int> timeOffRequestID)
        {
            var timeOffRequestIDParameter = timeOffRequestID.HasValue ?
                new ObjectParameter("TimeOffRequestID", timeOffRequestID) :
                new ObjectParameter("TimeOffRequestID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spSS_UpdateTimeOffRequestFromWeb", timeOffRequestIDParameter);
        }
    
        public virtual ObjectResult<spSS_TransDefTimeOff_Result> spSS_TransDefTimeOff()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spSS_TransDefTimeOff_Result>("spSS_TransDefTimeOff");
        }
    }
}
