//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPunchPair
    {
        public int tppID { get; set; }
        public Nullable<int> e_id { get; set; }
        public string e_idno { get; set; }
        public string e_name { get; set; }
        public Nullable<System.DateTime> DTPunchDate { get; set; }
        public Nullable<System.DateTime> DTimeIn { get; set; }
        public Nullable<System.DateTime> DTimeOut { get; set; }
        public Nullable<double> HoursWorked { get; set; }
        public string sType { get; set; }
        public string pCode { get; set; }
        public Nullable<bool> b_Processed { get; set; }
        public string DayID { get; set; }
        public Nullable<bool> bTrans { get; set; }
        public string sTCode { get; set; }
        public string sTDesc { get; set; }
        public string sTimeIn { get; set; }
        public string sTimeOut { get; set; }
        public Nullable<long> nWeekID { get; set; }
        public Nullable<int> nIsTransAbsent { get; set; }
        public Nullable<int> nPunchDateDayOfWeek { get; set; }
        public Nullable<int> nHRAttendanceCat { get; set; }
        public Nullable<int> nHRProcessedCode { get; set; }
        public Nullable<int> nHRReportCode { get; set; }
        public Nullable<int> nJobCodeID { get; set; }
    }
}
