//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPunchData
    {
        public int tpdID { get; set; }
        public Nullable<System.DateTime> DTPunchDate { get; set; }
        public Nullable<System.DateTime> DTPunchDateTime { get; set; }
        public Nullable<int> g_id { get; set; }
        public Nullable<int> e_id { get; set; }
        public string e_name { get; set; }
        public string e_idno { get; set; }
        public Nullable<short> e_group { get; set; }
        public string e_user { get; set; }
        public string e_mode { get; set; }
        public string e_type { get; set; }
        public string e_result { get; set; }
        public Nullable<bool> b_Processed { get; set; }
        public Nullable<bool> b_Modified { get; set; }
        public Nullable<int> nAdminID { get; set; }
        public string sModType { get; set; }
        public Nullable<int> nJobCodeID { get; set; }
        public string sNote { get; set; }
        public Nullable<int> nPunchType { get; set; }
        public Nullable<int> intTerminalType { get; set; }
        public Nullable<System.DateTime> DTPunchdate_Original { get; set; }
        public Nullable<System.DateTime> DTPunchDateTime_Original { get; set; }
        public Nullable<System.DateTime> DTPunchDateTime_Rounded { get; set; }
    }
}
