//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tPunchDate
    {
        public int tpdID { get; set; }
        public int e_id { get; set; }
        public string e_idno { get; set; }
        public string e_name { get; set; }
        public Nullable<short> e_group { get; set; }
        public Nullable<int> nSchedID { get; set; }
        public string DayID { get; set; }
        public Nullable<System.DateTime> DTPunchDate { get; set; }
        public Nullable<double> dblPunchHrs { get; set; }
        public string sType { get; set; }
        public Nullable<bool> b_Processed { get; set; }
        public string sPunchSummary { get; set; }
        public string sExceptions { get; set; }
        public string sDaySchedule { get; set; }
        public string sHoursSummary { get; set; }
        public Nullable<bool> bLocked { get; set; }
        public Nullable<double> dblREGULAR { get; set; }
        public Nullable<double> dblONEHALF { get; set; }
        public Nullable<double> dblDOUBLE { get; set; }
        public string sWeekID { get; set; }
        public Nullable<int> nCompanyID { get; set; }
        public Nullable<int> nDeptID { get; set; }
        public Nullable<int> nEmployeeTypeID { get; set; }
        public Nullable<double> dblMEAL { get; set; }
        public Nullable<double> dblOTHERS { get; set; }
        public Nullable<int> nAbsentStatus { get; set; }
        public Nullable<int> nJobTitleID { get; set; }
        public Nullable<long> nWeekID { get; set; }
        public int intPayrollLock { get; set; }
    }
}
