//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tReportWeek
    {
        public int tpwID { get; set; }
        public Nullable<int> e_id { get; set; }
        public string e_idno { get; set; }
        public string e_name { get; set; }
        public Nullable<int> nPayRuleID { get; set; }
        public string sPayRuleName { get; set; }
        public Nullable<int> nPayWeekNum { get; set; }
        public Nullable<System.DateTime> DTStartDate { get; set; }
        public Nullable<System.DateTime> DTEndDate { get; set; }
        public Nullable<double> dblREGULAR { get; set; }
        public Nullable<double> dblONEHALF { get; set; }
        public Nullable<double> dblDOUBLE { get; set; }
        public string sHoursSummary { get; set; }
        public string sWeekID { get; set; }
        public Nullable<int> nDept { get; set; }
        public string sDeptName { get; set; }
        public Nullable<int> nCompID { get; set; }
        public string sCompanyName { get; set; }
        public Nullable<int> nEmployeeType { get; set; }
        public string sEmployeeTypeName { get; set; }
        public Nullable<int> nJobTitleID { get; set; }
        public string sJobTitleName { get; set; }
        public Nullable<int> nScheduleID { get; set; }
        public string sScheduleName { get; set; }
        public Nullable<int> nPayPeriod { get; set; }
        public Nullable<int> nReviewStatus { get; set; }
        public Nullable<int> nReviewSupervisorID { get; set; }
        public string sSupervisorName { get; set; }
        public Nullable<long> nWeekID { get; set; }
        public Nullable<double> dblMEAL { get; set; }
        public Nullable<double> dblOTHERS { get; set; }
        public Nullable<int> nLocked { get; set; }
        public int intUserReviewed { get; set; }
        public Nullable<int> intUserReviewedID { get; set; }
        public string strUserReviewedName { get; set; }
        public Nullable<System.DateTime> dtUserReviewDate { get; set; }
    }
}
