//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSchedModDailyDetail
    {
        public int ID { get; set; }
        public Nullable<int> nUserID { get; set; }
        public string sUserName { get; set; }
        public string sWeekID { get; set; }
        public string sNote { get; set; }
        public Nullable<System.DateTime> dPunchDate { get; set; }
        public Nullable<System.DateTime> dPunchIn1 { get; set; }
        public Nullable<System.DateTime> dPunchOut1 { get; set; }
        public Nullable<System.DateTime> dPunchIn2 { get; set; }
        public Nullable<System.DateTime> dPunchOut2 { get; set; }
        public Nullable<System.DateTime> dPunchIn3 { get; set; }
        public Nullable<System.DateTime> dPunchOut3 { get; set; }
        public Nullable<System.DateTime> dPunchIn4 { get; set; }
        public Nullable<System.DateTime> dPunchOut4 { get; set; }
        public Nullable<int> nWorkDayType { get; set; }
        public Nullable<double> dblDayHours { get; set; }
        public Nullable<int> nSupervisorID { get; set; }
        public Nullable<System.DateTime> dModifiedDate { get; set; }
        public Nullable<int> nPunchNum { get; set; }
        public Nullable<int> nPayWeekNum { get; set; }
        public Nullable<int> nJobCodeID { get; set; }
        public Nullable<int> nSchedModPeriodSumm { get; set; }
    }
}
