//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tScheduleDayInfo
    {
        public int ID { get; set; }
        public Nullable<int> nSchedID { get; set; }
        public Nullable<int> nDayofWeek { get; set; }
        public Nullable<bool> bRight { get; set; }
        public Nullable<bool> bOvernight { get; set; }
        public Nullable<System.DateTime> dIn1Hr { get; set; }
        public Nullable<System.DateTime> dOut1Hr { get; set; }
        public Nullable<System.DateTime> dIn2Hr { get; set; }
        public Nullable<System.DateTime> dOut2Hr { get; set; }
        public Nullable<System.DateTime> dIn3Hr { get; set; }
        public Nullable<System.DateTime> dOut3Hr { get; set; }
        public Nullable<System.DateTime> dIn4Hr { get; set; }
        public Nullable<System.DateTime> dOut4Hr { get; set; }
        public Nullable<int> nJobCodeID { get; set; }
    }
}
