//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tTransDef
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> nTCode { get; set; }
        public string sTDesc { get; set; }
        public string pCode { get; set; }
        public Nullable<int> nIsAbsent { get; set; }
        public Nullable<int> nAttendaceCategory { get; set; }
        public string sAttendanceCategory { get; set; }
        public Nullable<int> nParentCode { get; set; }
        public string sParentCode { get; set; }
        public Nullable<int> nAccrualType { get; set; }
        public string sAccrualType { get; set; }
        public string sAccrualImportName { get; set; }
        public Nullable<int> nAttendanceRevision { get; set; }
        public Nullable<int> nTardinessRevision { get; set; }
        public Nullable<int> nCountsForVacationAccrual { get; set; }
        public Nullable<int> nCountsForSickAccrual { get; set; }
        public Nullable<double> dblPayRateMultiplier { get; set; }
        public Nullable<double> dblAdditionalPayAmount { get; set; }
        public Nullable<int> nCountForCompensationAccruals { get; set; }
        public string sCountForCompensationAccruals { get; set; }
        public Nullable<int> nIsMoneyTrans { get; set; }
        public Nullable<int> nIsMoneyAmountFixed { get; set; }
        public Nullable<decimal> decMoneyAmount { get; set; }
        public Nullable<int> nAttendanceRevLetter { get; set; }
        public Nullable<int> nTardinessRevLetter { get; set; }
        public Nullable<int> nCompforCompensationAccrual { get; set; }
        public string sCompforCompensationAccrual { get; set; }
        public Nullable<decimal> decPayRateMultiplier { get; set; }
        public Nullable<decimal> decPayRateOffset { get; set; }
        public Nullable<int> nPayRateTransaction { get; set; }
        public bool boolUseSickInFamily { get; set; }
        public Nullable<decimal> decMinimumAccrualTypeBalance { get; set; }
        public Nullable<decimal> decMaximumYearlyTaken { get; set; }
        public bool boolUseForTimesheetEditor { get; set; }
    }
}
