//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tuser
    {
        public int id { get; set; }
        public string name { get; set; }
        public string reg_date { get; set; }
        public string datelimit { get; set; }
        public string idno { get; set; }
        public string badmin { get; set; }
        public Nullable<int> padmin { get; set; }
        public string company { get; set; }
        public string dept { get; set; }
        public string phone { get; set; }
        public Nullable<short> group_id { get; set; }
        public byte[] cantgate { get; set; }
        public byte[] timegate { get; set; }
        public string validtype { get; set; }
        public string pwd { get; set; }
        public string cancard { get; set; }
        public string cardnum { get; set; }
        public string identify { get; set; }
        public string seculevel { get; set; }
        public byte[] fpdata { get; set; }
        public byte[] fpimage { get; set; }
        public byte[] fpname { get; set; }
        public byte[] face { get; set; }
        public byte[] voice { get; set; }
        public string remark { get; set; }
        public Nullable<int> antipass_state { get; set; }
        public string antipass_lasttime { get; set; }
        public Nullable<int> nCompanyID { get; set; }
        public Nullable<int> nDeptID { get; set; }
        public Nullable<int> nJobTitleID { get; set; }
        public Nullable<int> nGroupID { get; set; }
        public Nullable<int> nEmployeeType { get; set; }
        public Nullable<int> nStatus { get; set; }
        public string sNotes { get; set; }
        public byte[] objPhoto { get; set; }
        public Nullable<int> nPunchClockID { get; set; }
        public Nullable<int> nPayrollRuleID { get; set; }
        public Nullable<int> nScheduleID { get; set; }
        public Nullable<int> nSupervisorType { get; set; }
        public string sPwd { get; set; }
        public Nullable<int> nCompanyRest { get; set; }
        public Nullable<int> nDeptRest { get; set; }
        public Nullable<int> nCatRest { get; set; }
        public Nullable<bool> bEmpRecordsView { get; set; }
        public Nullable<bool> bEmpRecordsEdit { get; set; }
        public Nullable<bool> bEmpReportsView { get; set; }
        public Nullable<bool> bPunchMaintView { get; set; }
        public Nullable<bool> bPunchMaintEdit { get; set; }
        public Nullable<bool> bPunchSuperView { get; set; }
        public Nullable<bool> bReptPeriod { get; set; }
        public Nullable<bool> bReptHistorical { get; set; }
        public Nullable<bool> bReptAudit { get; set; }
        public Nullable<bool> bExportPayroll { get; set; }
        public Nullable<bool> bPayRuleView { get; set; }
        public Nullable<bool> bPayRuleEdit { get; set; }
        public Nullable<bool> bSchedView { get; set; }
        public Nullable<bool> bSchedEdit { get; set; }
        public Nullable<bool> bCompanySettings { get; set; }
        public Nullable<bool> bMonitor { get; set; }
        public Nullable<bool> bEmployeeImport { get; set; }
        public Nullable<bool> bRestrictClock { get; set; }
        public Nullable<int> nRestrickClock { get; set; }
        public Nullable<int> nSupervisorViewOptions { get; set; }
        public Nullable<bool> bHoursLostView { get; set; }
        public Nullable<bool> bHoursLostEdit { get; set; }
        public Nullable<int> nSickRule { get; set; }
        public Nullable<int> nVacationRule { get; set; }
        public Nullable<int> nEmployeeTypeRest { get; set; }
        public string sPwdHash { get; set; }
        public int intPositionID { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string FirstLastName { get; set; }
        public string SecondLastName { get; set; }
        public string ShortFullName { get; set; }
        public string Comments { get; set; }
        public Nullable<int> AutoShortFullName { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
