//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeAide.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewPay_UserBatchStatus
    {
        public System.Guid strBatchID { get; set; }
        public string strCompanyName { get; set; }
        public string strBatchDescription { get; set; }
        public System.DateTime dtBatchCreated { get; set; }
        public int intCreatedByID { get; set; }
        public string strCreateByName { get; set; }
        public System.DateTime dtBatchUpdates { get; set; }
        public int intBatchStatus { get; set; }
        public System.DateTime dtPayDate { get; set; }
        public Nullable<decimal> decBatchCompensationAmount { get; set; }
        public Nullable<decimal> decBatchDeductionAmount { get; set; }
        public string strStatusDescription { get; set; }
        public Nullable<decimal> decBatchTransactionHoursAmount { get; set; }
        public int intPayWeekNum { get; set; }
        public string strUserBatchStatus { get; set; }
        public int intUserID { get; set; }
        public string strUserName { get; set; }
        public string sHomeAddressLine1 { get; set; }
        public string sHomeAddressLine2 { get; set; }
        public string strCity { get; set; }
        public string strState { get; set; }
        public string strZipCode { get; set; }
        public Nullable<decimal> decBatchUserCompensations { get; set; }
        public Nullable<decimal> decBatchUserWithholdings { get; set; }
        public Nullable<decimal> decBatchNetPay { get; set; }
        public System.DateTime dtStartDatePeriod { get; set; }
        public System.DateTime dtEndDatePeriod { get; set; }
        public Nullable<int> intCompanyID { get; set; }
        public Nullable<int> intDepartmentID { get; set; }
        public Nullable<int> intSubdepartmentID { get; set; }
        public Nullable<int> intEmployeeTypeID { get; set; }
        public string strCompany { get; set; }
        public string strDepartment { get; set; }
        public string strSubdepartment { get; set; }
        public string strEmployeeType { get; set; }
        public string sSSN { get; set; }
        public string strBatchTypeName { get; set; }
        public int intPayMethodType { get; set; }
        public string strPayMethodType { get; set; }
        public int intBatchType { get; set; }
        public int intTemplateID { get; set; }
        public int intUserBatchStatus { get; set; }
        public Nullable<int> intDirectDepositCount { get; set; }
        public Nullable<int> intCheckCount { get; set; }
        public Nullable<int> ClosedByUserID { get; set; }
        public Nullable<System.DateTime> ClosedDateTime { get; set; }
    }
}
